name: Run

on:
  watch:
    types: [started]
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}
    - name: Push
      run: |
        if (git status --porcelain || echo err) | grep -q .; then
            echo '数据有更新，处理中...'
            git config user.name actionBot
            git config user.email github-actions@github.com
            git add .
            git commit -m "update" -q
            git push
            echo '处理完成'
        else
            echo '无更新，不处理'
        fi